Markus Doan-Le completed css-two-column-layout exercise
mdoanle/c0822-code-solutions pull request #22
Opened 2022-08-28 01:16 UTC by mdoanle

<img width="1440" alt="Screen Shot 2022-08-27 at 6 13 48 PM" src="https://user-images.githubusercontent.com/106715675/187053551-cdcff0b4-11c3-459d-98cd-aa1476cc1ecb.png">

2022-08-28 17:54 UTC, thebearingedge requested changes
Ok, good job so far, but there's a lot of duplication in your code. Try generalizing your typography CSS to start, so instead of `.top-right > h1` or `.africa-image` etc, try just making a `.heading` and `.image` and put all of the common styles in them. You should be able to cut like 20 lines of code that way.

2022-08-29 16:12 UTC, codingcodymiller requested changes

2022-08-29 16:12 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  justify-content: right;
Don't pollute your layout classes. You want to keep layout classes perfectly reusable, and augmenting their intended functionality immediately makes them less reusable. You should move this `justify-content` declaration to a separate class, and you can apply it in addition to the `row` class to any elements that need this behavior.

2022-08-29 16:12 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  text-align: center;
Don't pollute your layout classes. `column-` classes should only include `flex-basis` or `width` and nothing else. Please apply these additional declarations to a separate class that you can add in addition to the `column` class

2022-08-29 16:12 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
You should avoid applying styling to `id`s, please shift these to classes.

2022-08-29 16:12 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
You should avoid applying styling to `id`s, please shift these to classes.

2022-08-29 16:12 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +[value] {
This selector is kind of confusing, I would just add a class to the submit button that you can apply this styling to.

2022-08-29 19:12 UTC, codingcodymiller approved these changes

2022-08-29 19:14 UTC, merged